# Generated by Django 2.0.5 on 2018-10-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='label',
            field=models.TextField(blank=True),
        ),
    ]
