# Generated by Django 2.0.5 on 2018-06-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='CRD',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
