# Generated by Django 2.0.5 on 2018-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedupTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_threads', models.IntegerField(blank=True, null=True)),
                ('num_SF', models.IntegerField(blank=True, null=True)),
                ('seconds', models.DurationField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuplifyTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_threads', models.IntegerField(blank=True, null=True)),
                ('num_SF', models.IntegerField(blank=True, null=True)),
                ('num_rep', models.IntegerField(blank=True, null=True)),
                ('seconds', models.DurationField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_threads', models.IntegerField(blank=True, default=1, null=True)),
                ('num_records', models.IntegerField(blank=True, null=True)),
                ('batch_size', models.IntegerField(blank=True, null=True)),
                ('seconds', models.DurationField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='repcontact',
            old_name='workPhone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='sfcontact',
            old_name='workPhone',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='repcontact',
            name='match_ID',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='repcontact',
            name='otherPhone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sfcontact',
            name='ContactID',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sfcontact',
            name='otherPhone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='CRD',
            field=models.CharField(db_column='CRD', max_length=128),
        ),
    ]
