# Generated by Django 2.0.5 on 2018-08-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repcontact',
            name='misc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
