# Generated by Django 2.0.5 on 2018-10-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dedupper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
