# Generated by Django 2.0.5 on 2018-06-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=128)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('total_keys', models.IntegerField(blank=True, null=True)),
                ('completed', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_on',
            },
        ),
    ]
