# Generated by Django 2.0.5 on 2018-06-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0002_auto_20180621_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfcontact',
            name='ContactID',
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='CRD',
            field=models.CharField(db_column='CRD', max_length=128, unique=True),
        ),
    ]
