# Generated by Django 2.0.5 on 2018-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0002_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='CRD',
            field=models.CharField(db_column='CRD', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='area',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='boaName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='canSellDate',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fieldTrainerLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='homePhone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='levelGroup',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='levelLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailingCity',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailingStateProvince',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailingStreet',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailingZipPostalCode',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='otherEmail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='performanceLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='personalEmail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='region',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='regionalLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='suffix',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='territory',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='workEmail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='workPhone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='progress',
            name='label',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='CRD',
            field=models.CharField(db_column='CRD', max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='Phone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='area',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='boaName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='canSellDate',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='fieldTrainerLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='firstName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='homePhone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='lastName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='levelGroup',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='levelLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='mailingCity',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='mailingStateProvince',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='mailingStreet',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='mailingZipPostalCode',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='match_ID',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='otherEmail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='otherPhone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='performanceLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='personalEmail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='region',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='regionalLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='suffix',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='territory',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='type',
            field=models.CharField(choices=[('Undecided', 'Undecided'), ('Duplicate', 'Duplicate'), ('New Record', 'New Record')], default='Undecided', max_length=256),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='workEmail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='CRD',
            field=models.CharField(db_column='CRD', max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='ContactID',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='Phone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='area',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='boaName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='canSellDate',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='fieldTrainerLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='firstName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='homePhone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='lastName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='levelGroup',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='levelLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='mailingCity',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='mailingStateProvince',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='mailingStreet',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='mailingZipPostalCode',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='otherEmail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='otherPhone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='performanceLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='personalEmail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='region',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='regionalLeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='suffix',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='territory',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sfcontact',
            name='workEmail',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='simple',
            name='author',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='simple',
            name='category',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='simple',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='simple',
            name='type',
            field=models.CharField(choices=[('Undecided', 'Undecided'), ('Duplicate', 'Duplicate'), ('New Record', 'New Record')], default='Undecided', max_length=256),
        ),
    ]
