# Generated by Django 2.0.5 on 2018-10-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dedupper', '0002_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='')),
                ('link', models.URLField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='industry',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
