# Generated by Django 2.0.5 on 2018-10-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dedupper', '0003_auto_20181024_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completed_reps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
