# Generated by Django 2.0.5 on 2018-08-09 17:35

from django.db import migrations, models
import heroku_connect.db.models.base
import heroku_connect.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', heroku_connect.db.models.fields.ID(db_column='sfid', db_index=True, editable=False, max_length=18, null=True, sf_field_name='Id', unique=True, upsert=False)),
                ('system_mod_stamp', heroku_connect.db.models.fields.DateTime(db_column='systemmodstamp', db_index=True, null=True, sf_field_name='SystemModstamp', upsert=False)),
                ('is_deleted', heroku_connect.db.models.fields.Checkbox(db_column='isdeleted', sf_field_name='IsDeleted', upsert=False)),
                ('_hc_lastop', models.CharField(editable=False, help_text='Indicates the last sync operation Heroku Connect performed on the record', max_length=32, null=True)),
                ('_hc_err', models.TextField(editable=False, help_text='If the last sync operation by Heroku Connect resulted in an error then this column will contain a JSON object containing more information about the error', max_length=1024, null=True)),
                ('CRD', heroku_connect.db.models.fields.Text(db_column='crd__c', max_length=80, null=True, sf_field_name='CRD__c', upsert=False)),
                ('name', heroku_connect.db.models.fields.Text(db_column='name', max_length=80, null=True, sf_field_name='Name', upsert=False)),
                ('firstName', heroku_connect.db.models.fields.Text(db_column='firstname', max_length=80, null=True, sf_field_name='FirstName', upsert=False)),
                ('middleName', heroku_connect.db.models.fields.Text(db_column='middlename', max_length=80, null=True, sf_field_name='MiddleName', upsert=False)),
                ('lastName', heroku_connect.db.models.fields.Text(db_column='lastname', max_length=80, null=True, sf_field_name='LastName', upsert=False)),
                ('suffix', heroku_connect.db.models.fields.Text(db_column='suffix', max_length=80, null=True, sf_field_name='Suffix', upsert=False)),
                ('mailingStreet', heroku_connect.db.models.fields.Text(db_column='mailingstreet', max_length=80, null=True, sf_field_name='MailingStreet', upsert=False)),
                ('mailingCity', heroku_connect.db.models.fields.Text(db_column='mailingcity', max_length=80, null=True, sf_field_name='MailingCity', upsert=False)),
                ('mailingState', heroku_connect.db.models.fields.Text(db_column='mailingstate', max_length=80, null=True, sf_field_name='MailingState', upsert=False)),
                ('mailingPostalCode', heroku_connect.db.models.fields.Text(db_column='mailingpostalcode', max_length=80, null=True, sf_field_name='MailingPostalCode', upsert=False)),
                ('Phone', heroku_connect.db.models.fields.Phone(db_column='phone', max_length=40, null=True, sf_field_name='Phone', upsert=False)),
                ('mobilePhone', heroku_connect.db.models.fields.Phone(db_column='mobilephone', max_length=40, null=True, sf_field_name='MobilePhone', upsert=False)),
                ('homePhone', heroku_connect.db.models.fields.Phone(db_column='homephone', max_length=40, null=True, sf_field_name='HomePhone', upsert=False)),
                ('otherPhone', heroku_connect.db.models.fields.Phone(db_column='otherphone', max_length=40, null=True, sf_field_name='OtherPhone', upsert=False)),
                ('email', heroku_connect.db.models.fields.Email(db_column='email', max_length=80, null=True, sf_field_name='Email', upsert=False)),
                ('otherEmail', heroku_connect.db.models.fields.Email(db_column='other_email__c', max_length=80, null=True, sf_field_name='Other_Email__c', upsert=False)),
                ('personalEmail', heroku_connect.db.models.fields.Email(db_column='personal_email__c', max_length=80, null=True, sf_field_name='Personal_Email__c', upsert=False)),
            ],
            options={
                'db_table': 'salesforce"."contact',
                'managed': False,
            },
            bases=(heroku_connect.db.models.base._HerokuConnectSnitchMixin, models.Model),
        ),
    ]
