# Generated by Django 2.0.5 on 2018-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dedupper', '0003_auto_20181024_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
