# Generated by Django 2.0.5 on 2018-06-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0003_auto_20180629_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repcontact',
            old_name='match_ID',
            new_name='closest1_contactID',
        ),
        migrations.AddField(
            model_name='repcontact',
            name='closest2_contactID',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='repcontact',
            name='closest3_contactID',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
