# Generated by Django 2.0.5 on 2018-06-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0004_auto_20180606_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simple',
            old_name='closest',
            new_name='closest1',
        ),
    ]
