# Generated by Django 2.0.5 on 2018-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repcontact',
            name='area',
        ),
        migrations.RemoveField(
            model_name='repcontact',
            name='boaName',
        ),
        migrations.RemoveField(
            model_name='repcontact',
            name='canSellDate',
        ),
        migrations.RemoveField(
            model_name='repcontact',
            name='fieldTrainerLeader',
        ),
        migrations.RemoveField(
            model_name='repcontact',
            name='levelGroup',
        ),
        migrations.RemoveField(
            model_name='repcontact',
            name='levelLeader',
        ),
        migrations.RemoveField(
            model_name='repcontact',
            name='performanceLeader',
        ),
        migrations.RemoveField(
            model_name='repcontact',
            name='region',
        ),
        migrations.RemoveField(
            model_name='repcontact',
            name='regionalLeader',
        ),
        migrations.RemoveField(
            model_name='repcontact',
            name='territory',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='area',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='boaName',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='canSellDate',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='fieldTrainerLeader',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='levelGroup',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='levelLeader',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='performanceLeader',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='regionalLeader',
        ),
        migrations.RemoveField(
            model_name='sfcontact',
            name='territory',
        ),
        migrations.AddField(
            model_name='repcontact',
            name='middleName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='sfcontact',
            name='middleName',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
