# Generated by Django 2.0.5 on 2018-06-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0004_sfcontact_contactid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfcontact',
            name='CRD',
            field=models.CharField(db_column='CRD', max_length=128),
        ),
    ]
