# Generated by Django 2.0.5 on 2018-07-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0004_auto_20180630_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduptime',
            name='avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deduptime',
            name='num_dup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deduptime',
            name='num_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deduptime',
            name='num_undie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
