# Generated by Django 2.0.5 on 2018-06-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0005_auto_20180606_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple',
            name='closest1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_closest', to='dedupper.Simple'),
        ),
        migrations.AlterField(
            model_name='simple',
            name='closest2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_closest', to='dedupper.Simple'),
        ),
        migrations.AlterField(
            model_name='simple',
            name='closest3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_closest', to='dedupper.Simple'),
        ),
    ]
