# Generated by Django 2.0.5 on 2018-06-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0005_auto_20180621_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduptime',
            name='seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplifytime',
            name='seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadtime',
            name='seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
