# Generated by Django 2.0.5 on 2018-07-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0006_deduptime_current_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='repcontact',
            name='keySortedBy',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='deduptime',
            name='current_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='repcontact',
            name='type',
            field=models.CharField(choices=[('Undecided', 'Undecided'), ('Duplicate', 'Duplicate'), ('Manual Check', 'Manual Check'), ('New Record', 'New Record')], default='Undecided', max_length=256),
        ),
    ]
