# Generated by Django 2.0.5 on 2018-06-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0007_auto_20180615_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repcontact',
            name='CRD',
            field=models.CharField(db_column='CRD', max_length=128),
        ),
    ]
