# Generated by Django 2.0.5 on 2018-06-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0009_sfcontact_contactid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sfcontact',
            old_name='workPhone',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='sfcontact',
            name='otherPhone',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
