# Generated by Django 2.0.5 on 2018-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0010_auto_20180617_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfcontact',
            name='CRD',
            field=models.CharField(db_column='CRD', max_length=128),
        ),
    ]
