# Generated by Django 2.0.5 on 2018-06-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0011_auto_20180617_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repcontact',
            old_name='workPhone',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='repcontact',
            name='otherPhone',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
