# Generated by Django 2.0.5 on 2018-06-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0012_auto_20180617_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='repcontact',
            name='match_ID',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
