# Generated by Django 2.0.5 on 2018-06-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0013_repcontact_match_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedupTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_threads', models.IntegerField(blank=True, null=True)),
                ('num_SF', models.IntegerField(blank=True, null=True)),
                ('seconds', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuplifyTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_threads', models.IntegerField(blank=True, null=True)),
                ('num_SF', models.IntegerField(blank=True, null=True)),
                ('num_rep', models.IntegerField(blank=True, null=True)),
                ('seconds', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_threads', models.IntegerField(blank=True, default=1, null=True)),
                ('num_records', models.IntegerField(blank=True, null=True)),
                ('batch_size', models.IntegerField(blank=True, null=True)),
                ('seconds', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
