# Generated by Django 2.0.5 on 2018-06-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0014_deduptime_duplifytime_uploadtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduptime',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
