# Generated by Django 2.0.5 on 2018-06-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupper', '0015_deduptime_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduptime',
            name='seconds',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplifytime',
            name='seconds',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadtime',
            name='seconds',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
