"""
Django settings for dedupper_app project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import django_heroku
import dj_database_url
import psycopg2

#DATABASE_URL = os.environ['DATABASE_URL']
DATABASE_URL = 'postgres://avruysrbdidcpl:a115aa44a42574a665e2eb8058232ad46d34d487622c80d2433c96a4af773f71@ec2-23-21-129-50.compute-1.amazonaws.com:5432/d6cmhrlj40jglf'

conn = psycopg2.connect(DATABASE_URL, sslmode='require')


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ulm$oueq%7j8ao9(@7j_y_rc-(!0b!!u***q2(5bx(-$!!teyx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dedupper.apps.DedupperConfig',
    'django_tables2',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dedupper_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')] ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'dedupper_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

#heroku connnect
#https://devcenter.heroku.com/articles/heroku-connect

'''
host: ec2-23-21-129-50.compute-1.amazonaws.com
port: 5432 
database: d6cmhrlj40jglf
schema: salesforce 

external obj credentials
User: 8c536d5ac2454114b02c67954904b116
Password: e42c94f0132a4faaa1384b62c3166f91
server URL: https://odata-us.heroku.com/odata/v4/b85d58b34a3c4a37ba3fbc315e0987a4/	


DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 600,
             'ENGINE': 'django.db.backends.postgresql_psycopg2',
             'HOST': 'ec2-23-21-129-50.compute-1.amazonaws.com',
             'NAME': 'd6cmhrlj40jglf',
             'OPTIONS': {'sslmode': 'require'},
             'PASSWORD': '********************',
             'PORT': 5432,
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': 'avruysrbdidcpl'}}
             
Host        ec2-23-21-129-50.compute-1.amazonaws.com
Database    d6cmhrlj40jglf
User        avruysrbdidcpl
Port        5432
Password    a115aa44a42574a665e2eb8058232ad46d34d487622c80d2433c96a4af773f71
URI         postgres://avruysrbdidcpl:a115aa44a42574a665e2eb8058232ad46d34d487622c80d2433c96a4af773f71@ec2-23-21-129-50.compute-1.amazonaws.com:5432/d6cmhrlj40jglf
Heroku CLI  heroku pg:psql postgresql-vertical-55404 --app dedupper


DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
        'CONN_MAX_AGE': 600,
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'HOST': 'ec2-23-21-129-50.compute-1.amazonaws.com',
        'NAME': 'd6cmhrlj40jglf',
        'OPTIONS': {'sslmode': 'require'},
        'USER': 'avruysrbdidcpl',
        'PASSWORD': 'a115aa44a42574a665e2eb8058232ad46d34d487622c80d2433c96a4af773f71',
        'PORT': 5432,
        'TEST': {
            'CHARSET': None,
            'COLLATION': None,
            'MIRROR': None,
            'NAME': None
        },
        'TIME_ZONE': None,
    }
}
'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd6cmhrlj40jglf',
        'HOST': 'ec2-23-21-129-50.compute-1.amazonaws.com',
        'PORT': '5432',
        'USER': 'avruysrbdidcpl',
        'PASSWORD': 'a115aa44a42574a665e2eb8058232ad46d34d487622c80d2433c96a4af773f71',
    }
}

DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)

#Password validation
#https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

django_heroku.settings(locals())